extends Node2D

# NOM, EFFICACITE, PRECISION, ELEMENT, CIBLE, EFFET, NIVEAU, USAGER

var Spells = [
	["", 0, 0, ["None"], "R", -1, -1, []],
	["SOIN", 16, -1, ["None"], "SA", 0, 1, ["WM", "RM", "KN"], 4, 8, []],
	["DIA", 20, -1, ["Undead"], "AE", 1, 1, ["WM"], 3, 4, []],
	["GARDE", [8,7], -1, ["None"], "SA", 2, 1, ["WM", "RM", "KN"], 0, 8, []],
	["RUSE", [80,2], -1, ["None"], "C", 2, 1, ["WM", "RM", "KN"], 0, 3, []],
	["FEU", 10, -1, ["Fire"], "SE", 1, 1, ["BM", "RM", "NI"], 1, 11, []],
	["SOMMEIL", ["Sleep"], 24, ["Status"], "AE", 3, 1, ["BM", "RM", "NI"], 6, 9, []],
	["VISEE", [-20,2], 64, ["None"], "SE", 2, 1, ["BM", "RM", "NI"], 5, 9, []],
	["FOUDRE", 10, -1, ["Thdr"], "SE", 1, 1, ["BM", "RM", "NI"], 3, 9, []],
	["LUMIERE", ["Dark"], -1, ["None"], "SA", 4, 2, ["WM", "RM", "KN"], 6, 12, []],
	["PURE", ["Psn"], -1, ["None"], "SA", 4, 2, ["WM", "RM", "KN"], 6, 7, []],
	["ANTIFDR.", ["Thdr"], -1, ["None"], "AA", 5, 2, ["WM", "RM", "KN"], 0, 9, []],
	["FUMEE", [40,2], -1, ["None"], "SA", 2, 2, ["WM", "RM", "KN"], 6, 2, []],
	["GLACE", 20, -1, ["Ice"], "SE", 1, 2, ["BM", "RM", "NI"], 5, 4, []],
	["TENEBRE", ["Dark"], 24, ["Status"], "AE", 3, 2, ["BM", "RM", "NI"], 2, 2, []],
	["PUISS.", [14,1], -1, ["None"], "SA", 2, 2, ["BM", "RM", "NI"], 5, 10, []],
	["LENTEUR", -1, 64, ["Status"], "AE", 6, 2, ["BM", "RM", "NI"], 2, 3, []],
	["SOIN2", 33, -1, ["None"], "SA", 0, 3, ["WM", "RM", "KN"], 4, 7, []],
	["DIA2", 40, -1, ["Undead"], "AE", 3, 3, ["WM"], 3, 2, []],
	["ANTIFEU", ["Fire"], -1, ["None"], "AA", 5, 3, ["WM", "RM", "KN"], 0, 11, []],
	["GUERISON", 12, -1, ["None"], "AA", 0, 3, ["WM"], 4, 9, []],
	["FEU2", 30, -1, ["Fire"], "AE", 1, 3, ["BM", "RM", "NI"], 1, 10, []],
	["PARALYSI", ["Para"], 64, ["Status"], "SE", 4, 3, ["BM", "RM", "NI"], 2, 10, []],
	["FOUDRE2", 30, -1, ["Thdr"], "AE", 1, 3, ["BM", "RM", "NI"], 3, 10, []],
	["VISEE2", [-20,2], 40, ["None"], "AE", 2, 3, ["BM", "RM", "NI"], 5, 7, []],
	["SILENCE", ["Mute"], 107, ["Status"], "AE", 3, 4, ["WM", "RM"], 2, 5, []],
	["PEUR", [-40,9], 24, ["Status"], "AE", 2, 4, ["WM"], 2, 0, []],
	["ANTIGLC.", ["Ice"], -1, ["None"], "AA", 5, 4, ["BM", "RM"], 0, 4, []],
	["ANTISIL.", ["Mute"], -1, ["None"], "SA", 4, 4, ["WM", "RM"], 6, 5, []],
	["SOMMEIL2", ["Sleep"], 64, ["None"], "SE", 3, 4, ["BM", "RM", "NI"], 6, 4, []],
	["RAPIDITE", 1, -1, ["None"], "SA", 6, 4, ["BM", "RM", "NI"], 5, 12, []],
	["CONFUS.", ["Confuse"], 64, ["Status"], "AE", 2, 4, ["BM", "RM", "NI"], 2, 1, []],
	["GLACE2", 40, -1, ["Ice"], "AE", 1, 4, ["BM", "RM", "NI"], 5, 3, []],
	["SOIN3", 66, -1, ["None"], "SA", 0, 5, ["WM", "RM"], 4, 5, []],
	["VIE", 1, -1, ["Revive"], "SA", 0, 5, ["WM", "RW"], 4, 2],
	["DIA3", 60, -1, ["Undead"], "AE", 1, 5, ["WM"], 3, 0, []],
	["GUERISO2", 48, -1, ["None"], "AE", 1, 5, ["BM", "RM"], 4, 10, []],
	["FEU3", 50, -1, ["Fire"], "AE", 1, 5, ["BM", "RW"], 1, 0, []],
	["SEISME", ["Death"], 40, ["Earth"], "AE", 3, 5, ["BM","RW"], 6, 11, []],
	["TELEPORT", -1, -1, ["None"], "C", 8, 5, ["BM", "RW"], []],
	["LENTEUR2", -1, 64, ["None"], "SE", 6, 5, ["BM", "RM"], 2, 4, []],
	["ANIMA", ["Stn"], -1, ["None"], "SA", 4, 6, ["WM"], 6, 0, []],
	["SORTIE", -1, -1, ["None"], "C", 8, 6, ["WM","RW"], []],
	["GARDE2", [12,7], -1, ["None"], "AA", 2, 6, ["WM", "RW"], 0, 6, []],
	["FUMEE2", [40,2], -1, ["None"], "AA", 2, 6, ["WM", "RW"], 6, 1, []],
	["FOUDRE3", 60, -1, ["Thdr"], "AE", 1, 6, ["BM", "RW"], 3, 3, []],
	["MORT", ["Death"], 40, ["Death"], "SE", 3, 6, ["BM"], 7, 2, []],
	["TOXINE", ["Death"], 24, ["Psn"], "AE", 3, 5, ["BM"], 2, 6, []],
	["PARALYS2", ["Para"], 107, ["Status"], "SE", 3, 6, ["BM"], 2, 9, []],
	["SOIN4", ["FullHeal"], -1, ["None"], "SA", 4, 7, ["WW"], 4, 3, []],
	["DIA4", 80, -1, ["Undead"], "AE", 1, 7, ["WW"], 3, 5, []],
	["ANTIMORT", ["Psn","Time","Death","Earth"], -1, ["None"], "AA", 5, 7, ["WM", "RW"], 0, 0, []],
	["GUERISO3", 48, -1, ["None"], "AA", 0, 7, ["WM"], 4, 11, []],
	["GLACE3", 70, -1, ["Ice"], "AE", 1, 7, ["BM", "RW"], 5, 2, []],
	["STATUE", ["Stn"], 64, ["Stn"], "SE", 3, 7, ["BW"], 3, 12, []],
	["PUISS.2", [[16,1],[10,6]], -1, ["None"], "C", 2, 7, ["BW"], 5, 11, []],
	["TENEBRE2", ["Dark"], 107, ["Status"], "SE", 3, 7, ["BM"], 2, 12, []],
	["VIE2", 999, -1, ["Revive"], "SA", 4, 8, ["WW"], 4, 1, []],
	["SACRE", 80, -1, ["None"], "AE", 1, 8, ["WW"], 3, 1, []],
	["MUR", ["Status","Psn","Stn","Time","Death","Fire","Ice","Thdr","Earth"], -1, ["None"], "SA", 5, 8, ["WW"], 0, 12, []],
	["ANTIMUR", ["Status","Psn","Stn","Time","Death","Fire","Ice","Thdr","Earth"], 107, ["Time"], "SE", 7, 8, ["WW"], 5, 12, []],
	["ATOMIQUE", 100, -1, ["None"], "AE", 1, 8, ["BW"], 7, 11, []],
	["STOP", ["Para"], 48, ["Time"], "AE", 3, 8, ["BW"], 7, 12, []],
	["EXIL", ["Death"], 32, ["Time"], "AE", 3, 8, ["BW"], 7, 4, []],
	["MORT2",["Death"], 107, ["Death"], "SE", 3, 8, ["BW"], 7, 3, []],
]

var SpellDescriptions = [
	"",
	"Soigne entre 16 et 32 HP a un allie.",
	"Attaque contre les MORT-VIVANTS.\nATTAQUE MAGIQUE: 40.",
	"Augmente la DEFENSE d'un allie de 8.",
	"Augmente l'ESQUIVE du lanceur de 80.",
	"Attaque un ennemi.\nATTAQUE MAGIQUE: 20.\nElement: FEU.",
	"Peut infliger SOMMEIL sur les ennemis.\nPRECISION: 24.\nElement: STATUS.",
	"Peut reduire l'ESQUIVE d'un ennemi de 20.\nPRECISION: 64.",
	"Attaque un ennemi.\nATTAQUE MAGIQUE: 20.\nElement: FOUDRE.",
	"Gueris TENEBRE a un allie.",
	"Gueris POISON a un allie.",
	"Permet a toute l'equipe de resister a la FOUDRE.",
	"Augmente l'ESQUIVE d'un allie de 40.",
	"Attaque d'element GLACE sur un ennemi.\nATTAQUE MAGIQUE: 40.\nElement: GLACE.",
	"Peut infliger TENEBRE sur les ennemis.\nPRECISION: 24.\nElement: STATUS.",
	"Augmente l'ATTAQUE d'un allie de 14.",
	"Peut infliger LENTEUR a un ennemi.\nPRECISION: 64.\nElement: STATUS",
	"Soigne entre 33 et 66 HP a un allie .",
	"Attaque contre les MORT-VIVANTS.\nATTAQUE MAGIQUE: 80.",
	"Permet a toute l'equipe de resister au FEU.",
	"Soigne entre 12 et 24 HP a toute l'equipe.",
	"Attaque les ennemis.\nATTAQUE MAGIQUE: 60.\nElement: FEU.",
	"Peut infliger PARALYSIE a un ennemi.\nPRECISION: 64.\nElement: STATUS",
	"Attaque les ennemis.\nATTAQUE MAGIQUE: 60.\nElement: FOUDRE.",
	"Peut reduire l'ESQUIVE des ennemis de 20.\nPRECISION: 40.",
	"Peut infliger SILENCE a un ennemi.\nPRECISION: 107.\nElement: STATUS.",
	"Peut reduire le MORALE des ennemis de 40.\nPRECISION: 24.\nElement: STATUS.",
	"Permet a toute l'equipe de resister a la GLACE",
	"Gueris SILENCE a un allie.",
	"Peut infliger SOMMEIL sur un ennemi. PRECISION: 64.",
	"Applique RAPIDITE ou gueris LENTEUR a un allie.",
	"Peut infliger CONFUSION sur les ennemis. PRECISION: 64. Element: STATUS.",
	"Attaque les ennemis. ATTAQUE MAGIQUE: 80. Element: GLACE.",
	"Soigne entre 66 et 124 HP a un allie.",
	"Soigne 1 HP a un allie MORT.",
	"Attaque contre les MORT-VIVANTS. ATTAQUE MAGIQUE: 120.",
	"Soigne entre 24 et 48 HP a toute l'equipe.",
	"Attaque les ennemis. ATTAQUE MAGIQUE: 100. Element: FEU.",
	"Peut infliger MORT sur les ennemis. PRECISION: 40. Element: TERRE.",
	"Teleporte a la salle precedante d'un dongeon. Inutilisable hors-combat.",
	"Peut infliger LENTEUR a un ennemi. PRECISION: 64.",
	"Gueris PETRIFIE a un allie.",
	"Teleporte a l'entree d'un dongeon. Inutilisable hors-combat.",
	"Augmente la DEFENSE de l'equipe de 12.",
	"Augmente l'ESQUIVE de l'equipe de 40.",
	"Attaque les ennemis. ATTAQUE MAGIQUE: 120. Element: FOUDRE.",
	"Peut infliger MORT sur un ennemi. PRECISION: 40. Element: MORT.",
	"Peut infliger MORT sur les ennemis. PRECISION: 24. Element: POISON.",
	"Peut infliger PARALYSIE a un ennemi. PRECISION: 107. Element: STATUS.",
	"Soigne tous les HP d'un allie.",
	"Attaque contre les MORT-VIVANTS. ATTAQUE MAGIQUE: 160.",
	"Permet a toute l'equipe de resister a la MORT.",
	"Soigne entre 48 et 96 HP a toute l'equipe.",
	"Attaque les ennemis. ATTAQUE MAGIQUE: 140. Element: GLACE.",
	"Peut infliger PETRIFIE sur un ennemis. PRECISION: 64. Element: PETRIFIE.",
	"Augmente l'ATTAQUE de 14 et la PRECISION de 10 du lanceur.",
	"Peut infliger TENEBRE sur un ennemi. PRECISION: 107. Element: STATUS.",
	"Soigne tous les HP d'un allie MORT.",
	"Attaque les ennemis. ATTAQUE MAGIQUE: 160.",
	"Permet a un allie de resister a tous les elements.",
	"Peut enlever toute les resistance d'un ennemi. PRECISION: 107. Element: TEMPS.",
	"Attaque les ennemis. ATTAQUE MAGIQUE: 200.",
	"Peut infliger PARALYSIE sur un ennemi. PRECISION: 48. Element: TEMPS.",
	"Peut infliger MORT sur les ennemis. PRECISION: 32. Element: TEMPS.",
	"Peut infliger MORT sur un ennemi. PRECISION: 107. Element: MORT."
]

# NOM, EFFICACITE, PRECISION, ELEMENT, CIBLE, EFFET, NIVEAU, USAGER

var enemySpells = [
	["GIVRE",24,-1,["Ice"],"AE",1],
	["SURCHAUFFE",12,-1,["Fire"],"AE",1],
	["COUP D'OEIL","Stn",5,["Stn"],"SE",3],
	["REGARD","Para",0,["Status"],"SE",3],
	["FLASH","Dark",24,["Status"],"AE",3],
	["BRULURE",7,-1,["Fire"],"AE",1],
	["FISSURE","Death",16,["Earth"],"AE",3],
	["PLISSEMENT","Death",0,["Death"],"SE",3],
	["FIXEMENT",17,-1,["None"],"SE",1],
	["REGARD NOIR","Death",16,["Time"],"SE",3],
	["BLIZZARD",50,-1,["Ice"],"AE",1],
	["BRASIER",64,-1,["Fire"],"AE",1],
	["INFERNO",96,-1,["Fire"],"AE",1],
	["INCINERER",24,-1,["Fire"],"AE",1],
	["GAZ STATUE","Stn",5,["Stn","Psn"],"AE",3],
	["CHOC MENTAL","Para",0,["None"],"AE",3],
	["GAZ NOCIF",68,-1,["Psn"],"AE",1],
	["ECLAIR",76,-1,["Thdr"],"AE",1],
	["GAZ FATALE","Death",0,["Psn","Death"],"AE",3],
	["EBROUMMENT","Dark",24,["Status"],"SE",3],
	["NUCLEAIRE",80,-1,["None"],"AE",1],
	["ENCRE","Dark",24,["Status"],"AE",3],
	["DARD","Psn",0,["Psn"],"AE",3],
	["EBLOUISS.","Para",32,["Status"],"SE",3],
	["TOURBILLON",64,-1,["None"],"AE",1],
	["TORNADE",64,-1,["None"],"AE",1]
]

# Effets : 
#	Soin -> 0 | Dégats -> 1 | Stat UP/DOWN -> 2 | Status -> 3 | Guéris Status -> 4
#	Resist Element -> 5 | HitMul -> 6 ! Remove resistance -> 7 ! hors combat -> 8
# Quand tu fait Stat up ou Stat down au lieu de mettre juste la valeur d'efficacité
# Tu met, par exemple : [16, ID]
# ID -> HP_MAX : 0 | ATT : 1 | ESQ : 2 | INT : 3 | VIT : 4 
# LUCK : 5 | ACC : 6 | DEF : 7 | MDEF: 8 | MORAL: 9
