extends Node2D

# NOM, EFFICACITE, PRECISION, ELEMENT, CIBLE, EFFET, NIVEAU, USAGER

var Spells = [
	["", 0, 0, ["None"], "R", -1, -1, []],
	["SOIN", 16, -1, ["None"], "SA", 0, 1, ["WM", "RM", "KN"]],
	["DIA", 20, -1, ["Undead"], "AE", 1, 1, ["WM"]],
	["GARDE", [8,7], -1, ["None"], "SA", 2, 1, ["WM", "RM", "KN"]],
	["RUSE", [80,2], -1, ["None"], "C", 2, 1, ["WM", "RM", "KN"]],
	["FEU", 10, -1, ["Fire"], "SE", 1, 1, ["BM", "RM", "NI"]],
	["SOMMEIL", ["Sleep"], 24, ["Status"], "AE", 3, 1, ["BM", "RM", "NI"]],
	["VISEE", [-20,2], 64, ["None"], "SE", 2, 1, ["BM", "RM", "NI"]],
	["FOUDRE", 10, -1, ["Thdr"], "SE", 1, 1, ["BM", "RM", "NI"]],
	["LUMIERE", ["Dark"], -1, ["None"], "SA", 4, 2, ["WM", "RM", "KN"]],
	["PURE", ["Psn"], -1, ["None"], "SA", 4, 2, ["WM", "RM", "KN"]],
	["ANTIFDR.", ["Thdr"], -1, ["None"], "AA", 5, 2, ["WM", "RM", "KN"]],
	["FUMEE", [40,2], -1, ["None"], "SA", 2, 2, ["WM", "RM", "KN"]],
	["GLACE", 20, -1, ["Ice"], "SE", 1, 2, ["BM", "RM", "NI"]],
	["TENEBRE", ["Dark"], 24, ["Status"], "AE", 3, 2, ["BM", "RM", "NI"]],
	["PUISS.", [14,1], -1, ["None"], "SA", 2, 2, ["BM", "RM", "NI"]],
	["LENTEUR", -1, 64, ["Status"], "AE", 6, 2, ["BM", "RM", "NI"]],
	["SOIN2", 33, -1, ["None"], "SA", 0, 3, ["WM", "RM", "KN"]],
	["DIA2", 40, -1, ["Undead"], "AE", 3, 3, ["WM"]],
	["ANTIFEU", ["Fire"], -1, ["None"], "AA", 5, 3, ["WM", "RM", "KN"]],
	["GUERISON", 12, -1, ["None"], "AA", 0, 3, ["WM"]],
	["FEU2", 30, -1, ["Fire"], "AE", 1, 3, ["BM", "RM", "NI"]],
	["PARALYSI", ["Para"], 64, ["None"], "SE", 4, 3, ["BM", "RM", "NI"]],
	["FOUDRE2", 30, -1, ["Thdr"], "AE", 1, 3, ["BM", "RM", "NI"]],
	["VISEE2", [-20,2], 40, ["None"], "AE", 2, 3, ["BM", "RM", "NI"]],
	["SILENCE", ["Mute"], 107, ["Status"], "AE", 3, 4, ["WM", "RM"]],
	["PEUR", [-40,9], 24, ["Status"], "AE", 2, 4, ["WM"]],
	["ANTIGLC.", ["Ice"], -1, ["None"], "AA", 5, 4, ["BM", "RM"]],
	["ANTISIL.", ["Mute"], -1, ["None"], "SA", 4, 4, ["WM", "RM"]],
	["SOMMEIL2", ["Sleep"], 64, ["None"], "SE", 3, 4, ["BM", "RM", "NI"]],
	["RAPIDITE", 1, -1, ["None"], "SA", 6, 4, ["BM", "RM", "NI"]],
	["CONFUS.", ["Confuse"], 64, ["Status"], "AE", 2, 4, ["BM", "RM", "NI"]],
	["GLACE2", 40, -1, ["Ice"], "AE", 1, 4, ["BM", "RM", "NI"]],
	["SOIN3", 66, -1, ["None"], "SA", 0, 5, ["WM", "RM"]],
	["VIE", 1, -1, ["Revive"], "SA", 0, 5, ["WM", "RW"]],
	["DIA3", 60, -1, ["Undead"], "AE", 1, 5, ["WM"]],
	["GUERISO2", 40, -1, ["None"], "AE", 1, 5, ["BM", "RM"]],
	["FEU3", 50, -1, ["Fire"], "AE", 1, 5, ["BM", "RW"]],
	["SEISME", ["Death"], 40, ["Earth"], "AE", 3, 5, ["BM","RW"]],
	["TELEPORT", -1, -1, ["None"], "C", 8, 5, ["BM", "RW"]],
	["LENTEUR2", -1, 64, ["None"], "SE", 6, 5, ["BM", "RM"]],
	["ANIMA", ["Stn"], -1, ["None"], "SA", 4, 6, ["WM"]],
	["SORTIE", -1, -1, ["None"], "C", 8, 6, ["WM","RW"]],
	["GARDE2", [12,7], -1, ["None"], "AA", 2, 6, ["WM", "RW"]],
	["FUMEE2", [40,2], -1, ["None"], "AA", 2, 6, ["WM", "RW"]],
	["FOUDRE3", 60, -1, ["Thdr"], "AE", 1, 6, ["BM", "RW"]],
	["MORT", ["Death"], 40, ["Death"], "SE", 3, 6, ["BM"]],
	["TOXINE", ["Death"], 24, ["Psn"], "AE", 3, 5, ["BM"]],
	["PARALYS2", ["Para"], 107, ["Status"], "SE", 3, 6, ["BM"]],
	["SOIN4", ["FullHeal"], -1, ["None"], "SA", 4, 7, ["WW"]],
	["DIA4", 80, -1, ["Undead"], "AE", 1, 7, ["WW"]],
	["ANTIMORT", ["Psn","Time","Death","Earth"], -1, ["None"], "AA", 5, 7, ["WM", "RW"]],
	["GUERISO3", 48, -1, ["None"], "AA", 0, 7, ["WM"]],
	["GLACE3", 70, -1, ["Ice"], "AE", 1, 7, ["BM", "RW"]],
	["STATUE", ["Stn"], 64, ["Stn"], "SE", 3, 7, ["BW"]],
	["PUISS.2", [[16,1],[10,6]], -1, ["None"], "C", 2, 7, ["BW"]],
	["TENEBRE2", ["Dark"], 107, ["Status"], "SE", 3, 7, ["BM"]],
	["VIE2", 999, -1, ["Revive"], "SA", 4, 8, ["WW"]],
	["SACRE", 80, -1, ["None"], "AE", 1, 8, ["WW"]],
	["MUR", ["Status","Psn","Stn","Time","Death","Fire","Ice","Thdr","Earth"], -1, "None", "SA", 5, 8, ["WW"]],
	["ANTIMUR", ["Status","Psn","Stn","Time","Death","Fire","Ice","Thdr","Earth"], 107, "Time", "SE", 7, 8, ["WW"]],
	["ATOMIQUE", 100, -1, ["None"], "AE", 1, 8, ["BW"]],
	["STOP", ["Para"], 48, ["Time"], "AE", 3, 8, ["BW"]],
	["EXIL", ["Death"], 32, ["Time"], "AE", 3, 8, ["BW"]],
	["MORT2",["Death"], 107, ["Death"], "SE", 3, 8, ["BW"]],
]

# NOM, EFFICACITE, PRECISION, ELEMENT, CIBLE, EFFET, NIVEAU, USAGER

var enemySpells = [
	["GIVRE",24,-1,["Ice"],"AE",1],
	["SURCHAUFFE",12,-1,["Fire"],"AE",1],
	["COUP D'OEIL","Stn",5,["Stn"],"SE",3],
	["REGARD","Para",0,["Status"],"SE",3],
	["FLASH","Dark",24,["Status"],"AE",3],
	["BRULURE",7,-1,["Fire"],"AE",1],
	["FISSURE","Death",16,["Earth"],"AE",3],
	["PLISSEMENT","Death",0,["Death"],"SE",3],
	["FIXEMENT",17,-1,["None"],"SE",1],
	["REGARD NOIR","Death",16,["Time"],"SE",3],
	["BLIZZARD",50,-1,["Ice"],"AE",1],
	["BRASIER",64,-1,["Fire"],"AE",1],
	["INFERNO",96,-1,["Fire"],"AE",1],
	["INCINERER",24,-1,["Fire"],"AE",1],
	["GAZ STATUE","Stn",5,["Stn","Psn"],"AE",3],
	["CHOC MENTAL","Para",0,["None"],"AE",3],
	["GAZ NOCIF",68,-1,["Psn"],"AE",1],
	["ECLAIR",76,-1,["Thdr"],"AE",1],
	["GAZ FATALE","Death",0,["Psn","Death"],"AE",3],
	["EBROUMMENT","Dark",24,["Status"],"SE",3],
	["NUCLEAIRE",80,-1,["None"],"AE",1],
	["ENCRE","Dark",24,["Status"],"AE",3],
	["DARD","Psn",0,["Psn"],"AE",3],
	["EBLOUISS.","Para",32,["Status"],"SE",3],
	["TOURBILLON",64,-1,["None"],"AE",1],
	["TORNADE",64,-1,["None"],"AE",1]
]

# Effets : 
#	Soin -> 0 | Dégats -> 1 | Stat UP/DOWN -> 2 | Status -> 3 | Guéris Status -> 4
#	Resist Element -> 5 | HitMul -> 6 ! Remove resistance -> 7 ! hors combat -> 8
# Quand tu fait Stat up ou Stat down au lieu de mettre juste la valeur d'efficacité
# Tu met, par exemple : [16, ID]
# ID -> HP_MAX : 0 | ATT : 1 | ESQ : 2 | INT : 3 | VIT : 4 
# LUCK : 5 | ACC : 6 | DEF : 7 | MDEF: 8 | MORAL: 9
