extends Node2D

# NOM, STATS, SORT, PRIX, TYPE/RESIST, USAGER
# STATS SI ARME : [ATT, HIT%, CRIT], TYPE
# STATS SI ARMURE : [DEF, WEIGHT], RESIST

var items = [
	["", [0,0,0], 0, 0, ["None"], "res://Sprites/Icons/black.png"],
	["Bois", [12, 0, 10], 0, 10, ["None"],["NI", "BB"], "res://Sprites/Icons/nunchuck.png"],
	["Fer", [16, 0, 10], 0, 200, ["None"],["NI","BB"], "res://Sprites/Icons/nunchuck.png"],
	["Petite", [5, 10, 5], 0, 5, ["None"],["FI","TH","RM", "BM"], "res://Sprites/Icons/dagger.png"],
	["Large", [7, 10, 5], 0, 175, ["None"],["FI","TH","RM", "BM"], "res://Sprites/Icons/dagger.png"],
	["Argent", [10, 15, 5], 0, 800, ["None"],["FI","TH","RM", "BM"], "res://Sprites/Icons/dagger.png"],
	["Griffe", [22, 35, 5], 0, 65000, ["None"],["KN","NI","RW", "BW"], "res://Sprites/Icons/dagger.png"],
	["Bois", [6, 0, 1], 0, 5, ["None"],["FI","NI","BB","RM","WM", "BM"], "res://Sprites/Icons/staff.png"],
	["Solide", [12, 0, 1], 0, 24690, ["None"],["FI","NI","BB","WM", "BM"], "res://Sprites/Icons/staff.png"],
	["Fer", [14, 0, 1], 0, 200, ["None"],["FI","NI","BB"], "res://Sprites/Icons/staff.png"],
	["Guerison", [6, 0, 1], 20, 25000, ["None"],["NI","WM"], "res://Sprites/Icons/staff.png"],
	["Flamme", [12, 10, 1], 21, 25000, ["Fire"],["NI", "BM"], "res://Sprites/Icons/staff.png"],
	["Confus.", [15, 15, 1], 31, 50000, ["None"],["BW"], "res://Sprites/Icons/staff.png"],
	["Rapiere", [9, 5, 10], 0, 10, ["None"],["FI","TH","RM"], "res://Sprites/Icons/rapier.png"],
	["Fer", [9, 0, 1], 0, 10,["None"], ["FI","NI","WM"], "res://Sprites/Icons/hammer.png"],
	["Argent", [12, 5, 1], 0, 2500, ["None"],["FI","NI","WM"], "res://Sprites/Icons/hammer.png"],
	["Thor", [18, 15, 1], 23, 40000, ["Thdr"],["KN","NI","WW"], "res://Sprites/Icons/hammer.png"],
	["Combat", [16, 5, 3], 0, 550, ["None"],["FI","NI"], "res://Sprites/Icons/axe.png"],
	["Grande", [22, 5, 3], 0, 2000, ["None"],["FI","NI"], "res://Sprites/Icons/axe.png"],
	["Argent", [25, 10, 4], 0, 4500, ["None"],["FI","NI"], "res://Sprites/Icons/axe.png"],
	["Vive", [28, 15, 3], 18, 10000, ["Undead"],["FI","NI"], "res://Sprites/Icons/axe.png"],
	["Cimeterr", [10, 10, 5], 0, 200, ["None"],["FI","TH","RM"], "res://Sprites/Icons/katana.png"],
	["Fauchon", [15, 10, 5], 0, 450, ["None"],["FI","TH","RM"], "res://Sprites/Icons/katana.png"],
	["Sasuke", [33, 35, 30], 0, 60000, ["None"],["NI"], "res://Sprites/Icons/katana.png"],
	["Masamune", [56, 50, 10], 0, 60000, ["None"],["FI","TH","BB","RM","WM", "BM"], "res://Sprites/Icons/katana.png"],
	["Courte", [15, 10, 5], 0, 550, ["None"],["FI","NI","RM"], "res://Sprites/Icons/sword.png"],
	["Fer", [14, 0, 1], 0, 200, ["None"],["FI","NI","BB"], "res://Sprites/Icons/sword.png"],
	["Sabre", [13, 5, 10], 0, 450, ["None"],["FI","TH","RM"], "res://Sprites/Icons/sword.png"],
	["Longue", [20, 10, 5], 0, 1500, ["None"],["FI","NI","RM"], "res://Sprites/Icons/sword.png"],
	["Argent", [23, 15, 5], 0, 4000, ["None"],["FI","NI","RM"], "res://Sprites/Icons/sword.png"],
	["Flamme", [26, 20, 5], 0, 10000, ["Fire"],["FI","NI","RM"], "res://Sprites/Icons/sword.png"],
	["Glace", [29, 25, 5], 0, 15000, ["Ice"],["FI","NI","RM"], "res://Sprites/Icons/sword.png"],
	["Dragon", [19, 15, 10], 0, 8000, ["Dragon"],["FI","TH","RM"], "res://Sprites/Icons/sword.png"],
	["Geant", [21, 20, 5], 0, 8000, ["Giant"],["FI","NI","RM"], "res://Sprites/Icons/sword.png"],
	["Solaire", [32, 30, 5], 0, 20000, ["Undead"],["FI","NI","RM"], "res://Sprites/Icons/sword.png"],
	["Corail", [19, 15, 10], 0, 8000, ["Aqua"],["FI","TH","RM"], "res://Sprites/Icons/sword.png"],
	["Bestial", [18, 15, 5], 0, 6000, ["Beast"],["FI","NI","RM"], "res://Sprites/Icons/sword.png"],
	["Runique", [18, 15, 5], 0, 5000, ["Mage"],["FI","TH","RM"], "res://Sprites/Icons/sword.png"],
	["Defender", [30, 35, 5], 3, 40000, ["None"],["KN","NI","RW"], "res://Sprites/Icons/sword.png"],
	["Vorpal", [24, 25, 30], 0, 30000, ["None"],["KN","NI","RW"], "res://Sprites/Icons/sword.png"],
	["Toxique", [22, 20, 10], 38, 60000, ["None"],["KN","NI","RW"], "res://Sprites/Icons/sword.png"],
	["Xcalibur", [45, 35, 5], 0, 60000, ["Status","Psn","Stn","Time","Death","Fire","Ice","Thdr","Earth","Mage","Regen","Aqua","Beast","Undead","Giant","Dragon"],["KN"], "res://Sprites/Icons/sword.png"],
	["Tissu", [1, 2], 0, 10, ["None"], ["FI", "TH", "BB", "RM","WM","BW"], "res://Sprites/Icons/shirt.png"],
	["Blanc", [24, 2], 44, 2, ["Fire","Death"], ["WW"], "res://Sprites/Icons/shirt.png"],
	["Noir", [24, 2], 32, 2, ["Ice","Time"], ["BW"], "res://Sprites/Icons/shirt.png"],
	["Bois", [4, 8], 0, 50, ["None"],["FI","TH","BB","RM"], "res://Sprites/Icons/armor.png"],
	["Mailles", [15, 15], 0, 80, ["None"], ["FI", "NI", "RM"], "res://Sprites/Icons/armor.png"],
	["Fer", [24, 23], 0, 800, ["None"], ["FI", "NI"], "res://Sprites/Icons/armor.png"],
	["Acier", [34, 33], 0, 45000, ["None"], ["FI"], "res://Sprites/Icons/armor.png"],
	["Argent", [18, 8], 0, 7500, ["None"],["FI","NI","RM"], "res://Sprites/Icons/armor.png"],
	["Flamme", [34, 10], 0, 30000, ["Fire"],["FI","NI"], "res://Sprites/Icons/armor.png"],
	["Glace", [34, 10], 0, 30000, ["Ice"],["FI","NI"], "res://Sprites/Icons/armor.png"],
	["Opale", [42, 10], 0, 60000, ["Thdr"],["KN"], "res://Sprites/Icons/armor.png"],
	["Dragon", [42, 10], 0, 60000, ["Fire","Ice","Thdr"],["KN"], "res://Sprites/Icons/armor.png"],
	["Cuivre", [4, 1], 0, 100, ["None"], ["FI", "TH", "BB", "RM","WM","BW"], "res://Sprites/Icons/accesory.png"],
	["Argent", [15, 1], 0, 5000, ["None"], ["FI", "TH", "BB", "RM","WM","BW"], "res://Sprites/Icons/accesory.png"],
	["Or", [24, 1], 0, 50000, ["None"], ["FI", "TH", "BB", "RM","WM","BW"], "res://Sprites/Icons/accesory.png"],
	["Opale", [34, 1], 0, 65000, ["None"], ["FI", "TH", "BB", "RM","WM","BW"], "res://Sprites/Icons/accesory.png"],
	["Protect.", [8, 1], 0, 20000, ["Death"], ["FI", "TH", "BB", "RM","WM","BW"], "res://Sprites/Icons/accesory.png"],
	["Gants", [1, 1], 0, 60, ["None"], ["FI", "TH", "BB", "RM","WM","BW"], "res://Sprites/Icons/armlet.png"],
	["Cuivre", [2, 3], 0, 200, ["None"], ["FI", "NI"], "res://Sprites/Icons/armlet.png"],
	["Fer", [4, 5], 0, 750, ["None"], ["FI", "NI"], "res://Sprites/Icons/armlet.png"],
	["Argent", [6, 3], 0, 2500, ["None"], ["FI", "NI","RW"], "res://Sprites/Icons/armlet.png"],
	["Zeus", [6, 3], 23, 15000, ["None"], ["KN", "NI","RW"], "res://Sprites/Icons/armlet.png"],
	["Force", [6, 3], 55, 2500, ["None"], ["FI", "NI","RW"], "res://Sprites/Icons/armlet.png"],
	["Opale", [8, 3], 0, 20000, ["None"], ["KN"], "res://Sprites/Icons/armlet.png"],
	["Bois", [2, 0], 0, 15, ["None"], ["FI", "NI"], "res://Sprites/Icons/shield.png"],
	["Fer", [4, 0], 0, 100, ["None"], ["FI", "NI"], "res://Sprites/Icons/shield.png"],
	["Argent", [8, 0], 0, 2500, ["None"], ["FI", "NI"], "res://Sprites/Icons/shield.png"],
	["Flamme", [12, 0], 0, 10000, ["Fire"], ["FI", "NI"], "res://Sprites/Icons/shield.png"],
	["Glace", [12, 0], 0, 10000, ["Ice"], ["FI", "NI"], "res://Sprites/Icons/shield.png"],
	["Opale", [16, 0], 0, 15000, ["Thdr"], ["KN"], "res://Sprites/Icons/shield.png"],
	["Aegis", [16, 0], 0, 40000, ["Psn","Stn"], ["KN"], "res://Sprites/Icons/shield.png"],
	["Bocle", [2, 0], 0, 2500, ["None"], ["FI", "TH","RM"], "res://Sprites/Icons/bocle.png"],
	["Protect.", [8, 2], 0, 20000, ["None"], ["FI", "TH", "RM","WM","BW"], "res://Sprites/Icons/cape.png"],
	["Chapeau", [1, 1], 0, 80, ["None"], ["FI", "TH", "BB", "RM","WM","BW"], "res://Sprites/Icons/helmet.png"],
	["Bois", [3, 3], 0, 100, ["None"], ["FI", "NI"], "res://Sprites/Icons/helmet.png"],
	["Fer", [5, 5], 0, 450, ["None"], ["FI", "NI"], "res://Sprites/Icons/helmet.png"],
	["Argent", [6, 3], 0, 2500, ["None"], ["FI", "NI"], "res://Sprites/Icons/helmet.png"],
	["Opale", [8, 3], 0, 10000, ["None"], ["KN"], "res://Sprites/Icons/helmet.png"],
	["Guerison", [6, 3], 20, 20000, ["None"], ["KN", "NI"], "res://Sprites/Icons/helmet.png"],
	["Ruban", [1, 1], 0, 2, ["Status","Psn","Stn","Time","Death","Fire","Ice","Thdr","Earth"], ["FI", "TH", "BB", "RM","WM","BW"], "res://Sprites/Icons/ruban.png"]
]
